### ISSUE TITLE
API problem

### ISSUE THREAD

**Issue by alirzaghlmpr** [alirzaghlmpr/newsapp#1]
on localhost everything is ok but when i deploy it on heroku i got 426 error

**Comment by devXprite** [comment]
> on localhost everything is ok but when i deploy it on heroku i got 426 error

According to Newsapi pricing model in free plan **CORS is only enabled for localhost** so You can't make requests direct from the browser in Production. you'll have to use a backend. 

_https://newsapi.org/pricing_

**Comment by alirzaghlmpr** [comment]
> > on localhost everything is ok but when i deploy it on heroku i got 426 error
> 
> According to Newsapi pricing model in free plan **CORS is only enabled for localhost** so You can't make requests direct from the browser in Production. you'll have to use a backend.
> 
> _https://newsapi.org/pricing_

**Thanks <3
